env:
  browser: true
  es6: true
extends: ['eslint:recommended', 'plugin:react/recommended']
installedESLint: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
settings:
  - react
  - pragma: React
  - version: 15.0
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - warn
    - never
  comma-dangle:
    - error
    - only-multiline
  react/display-name:
    - off
